"""Add thinking_algorithm and life_wheel tables

Revision ID: 760f92cc1748
Revises: 9a3f9a0ae64e
Create Date: 2025-04-28 14:49:57.596636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760f92cc1748'
down_revision: Union[str, None] = '9a3f9a0ae64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
