"""add test_type to tests

Revision ID: 9a3f9a0ae64e
Revises: 91840009c2ca
Create Date: 2025-04-24 11:41:40.184319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3f9a0ae64e'
down_revision: Union[str, None] = '91840009c2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('test_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'test_type')
    # ### end Alembic commands ###
